server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/petistaan_pet

spring.datasource.username=root
spring.datasource.password=N@veen123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
mail.service.base.url=http://localhost:8083/mails
